/* WellOne Employee v105 — Admin-parity product manager */
(() => {
  'use strict';
  const $=id=>document.getElementById(id);
  const clean=v=>String(v??'').trim();
  const key=v=>clean(v).toLowerCase();
  const esc=v=>clean(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const price=v=>{const x=clean(v).replace(/[₹,]/g,'');return x||null;};
  const splitList=v=>Array.isArray(v)?v.map(clean).filter(Boolean):clean(v).split(/[|,\n]+/).map(clean).filter(Boolean);
  const slugify=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
  const nonNegativeInt=v=>{const n=Number.parseInt(String(v??'').replace(/[^0-9]/g,''),10);return Number.isFinite(n)&&n>0?n:0;};
  const SESSION_KEY='wellone_employee_session_v79';
  const PAGE_SIZE=20;
  const FIXED_PRODUCT_TERMS=Object.freeze([
    {key:'exchange',label:'7 Day Exchange Policy',description:'Eligible items can be exchanged within 7 days.'},
    {key:'delivery',label:'Free Delivery',description:'No delivery charge for this product.'},
    {key:'no-return',label:'No Return Allowed',description:'Returns and refunds are not available.'},
    {key:'pay-delivery',label:'Pay on Delivery',description:'Pay when your order is delivered.'},
    {key:'secure',label:'Secure Transaction',description:'Your order details are handled securely.'}
  ]);
  let client=null,categories=[],subcategories=[],currentProducts=[],offset=0,nextOffset=null,loading=false;
  let currentImages=[],newImageFiles=[],editingProductId='',saveInProgress=false,uploadGrant=null;

  function db(){
    if(!client) client=window.supabase.createClient(ADMIN_CONFIG.supabaseUrl,ADMIN_CONFIG.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},realtime:{params:{eventsPerSecond:10}}});
    return client;
  }
  function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch(_e){return null;}}
  function token(){return clean(session()?.token);}
  function requireSession(){const s=session();if(!s?.token)throw new Error('Employee login expired.');return s;}
  function status(text,type=''){const el=$('employeeManageStatus');if(!el)return;el.textContent=text;el.className=type||'';}
  function busy(text='Working...'){if($('employeeManageBusyText'))$('employeeManageBusyText').textContent=text;$('employeeManageBusy')?.classList.add('show');}
  function idle(){$('employeeManageBusy')?.classList.remove('show');}
  function sessionError(error){if(/expired|login/i.test(error?.message||'')){$('employeeLogoutBtn')?.click();return true;}return false;}
  function switchManagerView(which){
    $('employeeManageProducts')?.classList.toggle('active',which==='products');
    $('employeeManageEditor')?.classList.toggle('active',which==='editor');
    if(which==='products') document.body.classList.add('employee-manage-open');
  }
  async function openMode(mode){
    const sale=mode==='sale';
    $('employeeSaleTab')?.classList.toggle('active',sale); $('employeeManageTab')?.classList.toggle('active',!sale);
    $('employeeSaleView')?.classList.toggle('active',sale); $('employeeManageView')?.classList.toggle('active',!sale);
    document.body.classList.toggle('employee-manage-open',!sale);
    if(!sale){
      switchManagerView('products');
      try{await loadMeta();await loadProducts(true);}catch(error){if(!sessionError(error))status(error.message||'Could not load products.','error');}
    }
  }

  function policyKeyFromLabel(value){
    const label=key(value).replace(/[^a-z0-9]/g,'');
    if(label.includes('exchange'))return'exchange';
    if((label.includes('free')||label.includes('nocharge'))&&(label.includes('delivery')||label.includes('shipping')))return'delivery';
    if((label.includes('no')||label.includes('non'))&&(label.includes('return')||label.includes('refund')))return'no-return';
    if(label.includes('payondelivery')||label.includes('cashondelivery')||label==='cod')return'pay-delivery';
    if(label.includes('secure'))return'secure';
    return'';
  }
  function policyIconSvg(type){
    const icons={exchange:'<path d="M7 7h10l-2.5-2.5M17 17H7l2.5 2.5"/><path d="M17 7l2.5 2.5L17 12M7 17l-2.5-2.5L7 12"/>',delivery:'<path d="M3 6h11v10H3z"/><path d="M14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>','no-return':'<path d="M9 7H5v4"/><path d="M5.5 10.5A7 7 0 0 1 18 8"/><path d="M18.5 13.5A7 7 0 0 1 7 17"/><path d="M4 4l16 16"/>','pay-delivery':'<path d="M4 7h13a2 2 0 0 1 2 2v9H4z"/><path d="M4 7l2-3h11l2 3"/><circle cx="15.5" cy="13" r="2.5"/><path d="M15.5 11.5v3M14.5 12.2h1.5M14.5 13.8h1.5"/>',secure:'<path d="M12 3l7 3v5c0 4.7-2.8 8.1-7 10-4.2-1.9-7-5.3-7-10V6z"/><path d="M8.5 12.5l2.2 2.2 4.8-5"/>'};
    return `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[type]||icons.secure}</svg>`;
  }
  function renderTermChecks(selected=[]){
    const selectedKeys=new Set((selected||[]).map(policyKeyFromLabel).filter(Boolean));
    if(!$('productTermChecks'))return;
    $('productTermChecks').innerHTML=FIXED_PRODUCT_TERMS.map(term=>`<label class="policy-check"><input type="checkbox" value="${esc(term.label)}" ${selectedKeys.has(term.key)?'checked':''}><span class="policy-check-icon">${policyIconSvg(term.key)}</span><span class="policy-check-copy"><b>${esc(term.label)}</b><small>${esc(term.description)}</small></span></label>`).join('');
  }
  function selectedProductTerms(){return Array.from($('productTermChecks')?.querySelectorAll('input:checked')||[]).map(input=>input.value);}

  async function loadMeta(){
    requireSession();
    const {data,error}=await db().rpc('employee_manage_meta',{p_token:token()}); if(error)throw error;
    categories=(data?.categories||[]).map(c=>({id:clean(c.id),name:clean(c.name),active:c.is_active!==false})).filter(c=>c.id&&c.name);
    subcategories=(data?.subcategories||[]).map(s=>({id:clean(s.id),category_id:clean(s.category_id),name:clean(s.name),active:s.is_active!==false})).filter(s=>s.id&&s.name);
    fillCategoryInputs(); renderProductSubcategoryOptions(false);
  }
  function fillCategoryInputs(){
    const options=['<option value="">All categories</option>',...categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`)].join('');
    if($('productCategoryFilter'))$('productCategoryFilter').innerHTML=options;
    if($('category'))$('category').innerHTML='<option value="">Select category</option>'+categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');
  }
  function selectedCategory(){return categories.find(c=>c.id===clean($('category')?.value));}
  function productSubcategories(categoryId){return subcategories.filter(s=>s.category_id===clean(categoryId)&&s.active);}
  function setSubcategoryDropdown(open){const combo=$('subcategoryCombobox'),options=$('subcategoryOptions');if(!combo||!options)return;combo.classList.toggle('open',Boolean(open));options.hidden=!open;$('subcategory')?.setAttribute('aria-expanded',String(Boolean(open)));$('subcategoryToggle')?.setAttribute('aria-expanded',String(Boolean(open)));}
  function renderProductSubcategoryOptions(open=false){
    const input=$('subcategory'),toggle=$('subcategoryToggle'),options=$('subcategoryOptions'),hint=$('subcategoryHint');if(!input||!toggle||!options||!hint)return;
    const category=selectedCategory();
    if(!category){input.disabled=true;toggle.disabled=true;input.placeholder='Select category first';hint.textContent='Select a category first.';options.innerHTML='';setSubcategoryDropdown(false);return;}
    input.disabled=false;toggle.disabled=false;input.placeholder='Select subcategory';
    const value=clean(input.value),all=productSubcategories(category.id),visible=value?all.filter(s=>key(s.name).includes(key(value))):all,exact=value?all.find(s=>key(s.name)===key(value)):null;
    options.innerHTML=visible.length?visible.map(s=>`<button type="button" class="subcategory-option${exact?.id===s.id?' selected':''}" data-subcategory-option="${esc(s.name)}"><span>${esc(s.name)}</span><small>Existing</small></button>`).join(''):`<div class="subcategory-empty">${value?`<b>Create “${esc(value)}”</b><small>This new subcategory will be added under ${esc(category.name)} when you save.</small>`:`<b>No subcategories yet</b><small>Type a name to create one under ${esc(category.name)}.</small>`}</div>`;
    hint.textContent=exact?`Existing subcategory selected under ${category.name}.`:value?`“${value}” will be created under ${category.name} when you save.`:all.length?`${all.length} subcategor${all.length===1?'y':'ies'} available under ${category.name}.`:`No existing subcategories under ${category.name}.`;
    setSubcategoryDropdown(open);
  }

  function normalizeListProduct(row){return{id:clean(row.id),name:clean(row.name),categoryId:clean(row.category_id),category:clean(row.category_name),subcategory:clean(row.subcategory_name),price:price(row.price)||'',mrp:price(row.mrp)||'',image:clean(row.main_image_url),status:clean(row.status||'active'),stockStatus:clean(row.stock_status||'in_stock'),stockQuantity:Math.max(0,Number(row.stock_quantity||0)),trackInventory:row.track_inventory===true,barcode:clean(row.barcode),barcodeEnabled:row.barcode_enabled===true,sizes:clean(row.sizes||'Standard')};}
  function productListHtml(products){return(products||[]).map(p=>`<article class="admin-product" data-product-row="${esc(p.id)}"><img loading="lazy" decoding="async" src="${esc(p.image)}" onerror="this.style.display='none'"><div><b>${esc(p.name)}</b><small>${esc(p.category)}${p.subcategory?' / '+esc(p.subcategory):''} · ${p.mrp?`<del>₹${esc(p.mrp)}</del> `:''}${p.price?'₹'+esc(p.price):'Ask price'} · ${p.stockStatus==='out_of_stock'?'Out of stock':p.status!=='active'?'Hidden':'Available'}${p.trackInventory?` · ${p.stockQuantity} unit${p.stockQuantity===1?'':'s'} in stock`:''}${p.barcodeEnabled&&p.barcode?` · Barcode ${esc(p.barcode)}`:''} · ${esc(p.sizes||'Standard')}</small></div><button type="button" data-edit="${esc(p.id)}">Edit</button></article>`).join('');}
  async function loadProducts(reset=true){
    if(loading)return;if(!reset&&(nextOffset===null||nextOffset===undefined))return;requireSession();loading=true;
    if(reset){currentProducts=[];offset=0;nextOffset=null;$('productList').innerHTML='<div class="empty">Loading products...</div>';}
    try{
      const categoryName=clean($('productCategoryFilter')?.value),category=categoryName?categories.find(c=>key(c.name)===key(categoryName)):null;
      const {data,error}=await db().rpc('employee_manage_list_products',{p_token:token(),p_query:clean($('searchProducts')?.value),p_category_id:category?.id||null,p_offset:offset,p_limit:PAGE_SIZE});if(error)throw error;
      const all=(data?.items||[]).map(normalizeListProduct),hasMore=Boolean(data?.has_more),list=all.slice(0,PAGE_SIZE);
      currentProducts=reset?list:currentProducts.concat(list.filter(x=>!currentProducts.some(y=>y.id===x.id)));
      offset+=list.length;nextOffset=hasMore?offset:null;
      $('productList').innerHTML=currentProducts.length?productListHtml(currentProducts):'<div class="empty">No products found.</div>';
      $('loadMoreProductsBtn')?.classList.toggle('hide',!hasMore);status(`Loaded ${currentProducts.length} product${currentProducts.length===1?'':'s'} ✅`,'ok');
    }finally{loading=false;}
  }

  function renderImagePreviews(){
    if(!$('previewGrid'))return;
    const existing=currentImages.map((img,i)=>`<div class="preview-item"><img src="${esc(img.url)}"><button type="button" data-remove-existing-image="${i}">×</button></div>`).join('');
    const fresh=newImageFiles.map((file,i)=>`<div class="preview-item"><img src="${esc(URL.createObjectURL(file))}"><button type="button" data-remove-new-image="${i}">×</button></div>`).join('');
    $('previewGrid').innerHTML=existing+fresh;
  }
  function clearProductImages(){currentImages=[];newImageFiles=[];if($('photoInput'))$('photoInput').value='';renderImagePreviews();}
  function resetProduct(showEditor=true){
    editingProductId='';saveInProgress=false;$('productForm')?.reset();if($('editId'))$('editId').value='';if($('availability'))$('availability').value='in_stock';if($('productStockQuantity'))$('productStockQuantity').value='0';if($('variantSetupMode'))$('variantSetupMode').value='simple';if($('variantBulkSharedImageName'))$('variantBulkSharedImageName').textContent='No image selected';currentImages=[];newImageFiles=[];renderImagePreviews();renderTermChecks();renderVariantRows([]);renderProductSubcategoryOptions(false);updateInventoryControls();if($('formTitle'))$('formTitle').textContent='Add product';if($('saveBtn'))$('saveBtn').textContent='Save Product';if($('deleteBtn'))$('deleteBtn').style.display='none';$('cancelEditBtn')?.classList.add('hide');if(showEditor)switchManagerView('editor');
  }

  function variantOptionLabel(){return clean($('optionTitle')?.value)||'Size / option';}
  function inferredVariantMode(){const rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]);if(!rows.length)return'simple';return rows.some(row=>clean(row.querySelector('.variant-color')?.value))?'color_option':'option';}
  function variantRowHtml(v={},i=0){
    const color=clean(v.color||v.unit),size=clean(v.size||v.label),images=Array.isArray(v.images)?v.images:[],hasImages=images.length>0,hasPrice=Boolean(price(v.price)||price(v.mrp));
    const imgs=images.map((url,idx)=>`<div class="variant-img-chip"><img src="${esc(url)}"><button type="button" data-remove-variant-existing="${idx}">×</button></div>`).join('');
    return `<article class="variant-row" data-variant-id="${esc(v.id||'')}" data-variant-index="${i}" data-existing-images='${esc(JSON.stringify(images))}' data-existing-paths='${esc(JSON.stringify(v.storagePaths||[]))}'><div class="variant-title"><b>${esc([color,size].filter(Boolean).join(' · ')||`Option ${i+1}`)}</b><button type="button" data-remove-variant="${i}">Remove</button></div><div class="field-row variant-dimensions-row"><label class="variant-color-field">Colour<input class="variant-color" value="${esc(color)}" placeholder="Brown / Blue / Black"></label><label><span class="variant-option-name">Size / option</span><input class="variant-size" value="${esc(size)}" placeholder="8 / Large / 500ml"></label></div><div class="field-row variant-stock-price-row"><label>Availability<select class="variant-availability"><option value="in_stock" ${clean(v.stockStatus||v.stock_status||'in_stock')==='in_stock'?'selected':''}>Available</option><option value="out_of_stock" ${clean(v.stockStatus||v.stock_status)==='out_of_stock'?'selected':''}>Out of stock</option><option value="hidden" ${clean(v.stockStatus||v.stock_status)==='hidden'?'selected':''}>Hide option</option></select></label><label class="variant-quantity-wrap">Quantity<input class="variant-quantity" type="number" min="0" step="1" inputmode="numeric" value="${Math.max(0,Number(v.stockQuantity??v.stock??0)||0)}"></label></div><label class="switch-row compact-switch variant-separate-price-row"><span><b>Separate rate for this option</b><small>Leave off to use the main product price.</small></span><input class="variant-separate-price" type="checkbox" ${hasPrice?'checked':''}></label><div class="field-row variant-price-fields ${hasPrice?'':'hide'}"><label>MRP <small class="optional">Optional</small><input class="variant-mrp" inputmode="numeric" value="${esc(v.mrp||'')}"></label><label>Final price<input class="variant-price" inputmode="numeric" value="${esc(v.price||'')}"></label></div><label class="switch-row compact-switch variant-separate-image-row"><span><b class="variant-image-toggle-title">Separate image</b><small class="variant-image-toggle-help">Off = use the main product image.</small></span><input class="variant-separate-image" type="checkbox" ${hasImages?'checked':''}></label><div class="variant-image-section ${hasImages?'':'hide'}"><div class="variant-images">${imgs}<label class="mini-upload">+ Image<input class="variant-files" type="file" accept="image/*" hidden></label></div></div></article>`;
  }
  function initializeVariantRow(row){if(!row)return;row.__variantFiles=[];updateVariantRowTitle(row);updateVariantInheritanceUI();updateInventoryControls();}
  function renderVariantRows(list=[]){
    const rows=(Array.isArray(list)?list:[]).map(v=>({...v,images:Array.isArray(v?.images)?[...v.images]:[],storagePaths:Array.isArray(v?.storagePaths)?[...v.storagePaths]:[]}));
    const groups=new Map();rows.forEach(r=>{const c=clean(r.color||r.unit);if(!c)return;const k=key(c);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);});
    groups.forEach(group=>{const source=group.find(r=>r.images?.length);if(!source)return;group[0].images=[...source.images];group[0].storagePaths=[...(source.storagePaths||[])];group.slice(1).forEach(r=>{r.images=[];r.storagePaths=[];});});
    $('variantList').innerHTML=rows.length?rows.map(variantRowHtml).join(''):'<div class="empty variant-empty"><b>No separate options added.</b><span>Keep this as a simple product, or choose an option setup above.</span></div>';
    $('variantList').querySelectorAll('.variant-row').forEach(initializeVariantRow);if($('variantSetupMode'))$('variantSetupMode').value=rows.length?(rows.some(v=>clean(v.color||v.unit))?'color_option':'option'):'simple';updateVariantModeUI();renderVariantGroupControls();
  }
  function appendVariantRow(data={}){if($('variantSetupMode')?.value==='simple')$('variantSetupMode').value=clean(data.color)?'color_option':'option';const list=$('variantList');list.querySelector('.variant-empty')?.remove();const index=list.querySelectorAll('.variant-row').length;list.insertAdjacentHTML('beforeend',variantRowHtml(data,index));initializeVariantRow(list.lastElementChild);updateVariantModeUI();}
  function updateVariantRowTitle(row){if(!row)return;const index=Number(row.dataset.variantIndex||0)+1,color=clean(row.querySelector('.variant-color')?.value),size=clean(row.querySelector('.variant-size')?.value);const title=row.querySelector('.variant-title b');if(title)title.textContent=[color,size].filter(Boolean).join(' · ')||`Variant ${index}`;}
  function variantRowOwnImages(row){const existing=JSON.parse(row?.dataset.existingImages||'[]'),files=Array.isArray(row?.__variantFiles)?row.__variantFiles:[];return existing.length>0||files.length>0;}
  function updateVariantInheritanceUI(){
    const mode=clean($('variantSetupMode')?.value||inferredVariantMode()),rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]),first=new Map();
    rows.forEach(row=>{const color=clean(row.querySelector('.variant-color')?.value);if(mode==='color_option'&&color&&!first.has(key(color)))first.set(key(color),row);});
    rows.forEach(row=>{const color=clean(row.querySelector('.variant-color')?.value),lead=mode==='color_option'&&color&&first.get(key(color))===row,toggle=row.querySelector('.variant-separate-image'),toggleRow=row.querySelector('.variant-separate-image-row'),title=row.querySelector('.variant-image-toggle-title'),help=row.querySelector('.variant-image-toggle-help'),section=row.querySelector('.variant-image-section');if(lead){if(toggle){toggle.checked=true;toggle.disabled=true;}if(title)title.textContent=`${color} image`;if(help)help.textContent=`Used automatically for every ${variantOptionLabel().toLowerCase()} in ${color}.`;toggleRow?.classList.remove('hide');section?.classList.remove('hide');}else{if(toggle)toggle.disabled=false;if(mode==='color_option'){if(toggle)toggle.checked=false;toggleRow?.classList.add('hide');section?.classList.add('hide');}else{if(title)title.textContent='Separate image for this option';if(help)help.textContent='Off = use the main product image.';toggleRow?.classList.toggle('hide',mode==='simple');section?.classList.toggle('hide',!(toggle?.checked||variantRowOwnImages(row)));}}const rate=row.querySelector('.variant-separate-price');row.querySelector('.variant-price-fields')?.classList.toggle('hide',!rate?.checked);});
  }
  function variantRowsAllSeparatePrice(){const rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]);return rows.length>0&&rows.every(row=>Boolean(row.querySelector('.variant-separate-price')?.checked)&&Boolean(price(row.querySelector('.variant-price')?.value)));}
  function syncMainPricingVisibility(){const mode=clean($('variantSetupMode')?.value||inferredVariantMode()),bulk=Boolean($('variantBulkSeparatePrice')?.checked);$('mainPricingSection')?.classList.toggle('hide',mode!=='simple'&&(bulk||variantRowsAllSeparatePrice()));}
  function buildVariantBulkRateTable(){
    const table=$('variantBulkRateTable');if(!table)return;const rate=Boolean($('variantBulkSeparatePrice')?.checked),qty=Boolean($('variantBulkSeparateQty')?.checked),values=String($('variantBulkSizes')?.value||'').split(/[,\n|]+/).map(clean).filter(Boolean);$('variantBulkQtyWrap')?.classList.toggle('hide',qty);table.classList.toggle('hide',(!rate&&!qty)||!values.length);syncMainPricingVisibility();if((!rate&&!qty)||!values.length){table.innerHTML='';return;}const oldMrp=new Map(Array.from(table.querySelectorAll('[data-bulk-mrp]')).map(x=>[key(x.dataset.bulkMrp),x.value])),oldRate=new Map(Array.from(table.querySelectorAll('[data-bulk-rate]')).map(x=>[key(x.dataset.bulkRate),x.value])),oldQty=new Map(Array.from(table.querySelectorAll('[data-bulk-qty]')).map(x=>[key(x.dataset.bulkQty),x.value]));table.className=`variant-rate-table ${rate&&qty?'has-rate has-qty':rate?'has-rate':'has-qty'}`;table.innerHTML=`<div class="variant-rate-head"><span>${esc(variantOptionLabel())}</span>${rate?'<span>MRP</span><span>Final price</span>':''}${qty?'<span>Quantity</span>':''}</div>${values.map(value=>`<label class="variant-rate-row"><b>${esc(value)}</b>${rate?`<input data-bulk-mrp="${esc(value)}" inputmode="numeric" placeholder="MRP" value="${esc(oldMrp.get(key(value))||'')}"><input data-bulk-rate="${esc(value)}" inputmode="numeric" placeholder="Final ₹" value="${esc(oldRate.get(key(value))||'')}">`:''}${qty?`<input data-bulk-qty="${esc(value)}" inputmode="numeric" min="0" step="1" type="number" placeholder="0" value="${esc(oldQty.get(key(value))||'0')}">`:''}</label>`).join('')}`;
  }
  function bulkMrpFor(v){return price(Array.from($('variantBulkRateTable')?.querySelectorAll('[data-bulk-mrp]')||[]).find(x=>key(x.dataset.bulkMrp)===key(v))?.value);}
  function bulkRateFor(v){return price(Array.from($('variantBulkRateTable')?.querySelectorAll('[data-bulk-rate]')||[]).find(x=>key(x.dataset.bulkRate)===key(v))?.value);}
  function bulkQtyFor(v){return nonNegativeInt(Array.from($('variantBulkRateTable')?.querySelectorAll('[data-bulk-qty]')||[]).find(x=>key(x.dataset.bulkQty)===key(v))?.value);}
  function updateVariantModeUI(){
    const mode=clean($('variantSetupMode')?.value||inferredVariantMode()),colorMode=mode==='color_option',simple=mode==='simple';$('variantBulkColorWrap')?.classList.toggle('hide',!colorMode);document.querySelectorAll('#employeeManageView .variant-color-field').forEach(x=>x.classList.toggle('hide',!colorMode));document.querySelectorAll('#employeeManageView .variant-option-name').forEach(x=>x.textContent=variantOptionLabel());if($('variantBulkOptionLabel'))$('variantBulkOptionLabel').textContent=colorMode?`${variantOptionLabel()}s for this colour`:`${variantOptionLabel()} values`;if($('variantBulkSizes'))$('variantBulkSizes').placeholder=colorMode?'5, 6, 7, 8':'100ml, 250ml, 500ml';if($('variantModeHelp'))$('variantModeHelp').textContent=simple?'No selectable options. Use the main price, images and stock.':colorMode?'Customers choose colour first, then an available option inside that colour.':'Use this for size-only, ml, litre, weight, pack, measurement or any custom option.';if($('variantBulkHelp'))$('variantBulkHelp').textContent=colorMode?'Creates one exact stock row per colour + option. Each row remains independently editable.':'Choose an optional image, enter one or more values, then add. Add the next value/batch with another image whenever needed.';$('variantBulkColor')?.closest('label')?.classList.toggle('hide',!colorMode);$('variantList')?.classList.toggle('is-simple-mode',simple);$('variantBulkPanel')?.classList.toggle('hide',simple);$('addVariantBtn')?.classList.toggle('hide',simple);$('variantBulkImageWrap')?.classList.toggle('hide',simple);if($('variantBulkImageTitle'))$('variantBulkImageTitle').textContent=colorMode?'Colour image':'Option image';if($('variantBulkImageHelp'))$('variantBulkImageHelp').textContent=colorMode?`One image is reused automatically for every ${variantOptionLabel().toLowerCase()} in this colour.`:'Optional. The selected image is attached immediately to the option value(s) you add now. Add another batch with a different image whenever needed.';if($('variantBulkSharedImageBtn'))$('variantBulkSharedImageBtn').textContent=colorMode?'Add colour image':'Add option image';$('productImageStep')?.classList.toggle('hide',colorMode);$('optionTitleRow')?.classList.toggle('hide',simple);updateVariantInheritanceUI();buildVariantBulkRateTable();syncMainPricingVisibility();renderVariantGroupControls();
  }
  function handleVariantModeChange(){const mode=clean($('variantSetupMode')?.value||'simple'),rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]);if(mode==='simple'&&rows.length){if(!confirm('Switch to a simple product and remove the option rows from this form?')){$('variantSetupMode').value=inferredVariantMode();updateVariantModeUI();return;}renderVariantRows([]);return;}if(mode==='option'){const withColor=rows.filter(row=>clean(row.querySelector('.variant-color')?.value));if(withColor.length&&!confirm('Remove colour names and keep these as option-only rows?')){$('variantSetupMode').value='color_option';updateVariantModeUI();return;}withColor.forEach(row=>{row.querySelector('.variant-color').value='';updateVariantRowTitle(row);});}updateVariantModeUI();updateInventoryControls();}
  function effectiveVariantStatus(row){const manual=clean(row.querySelector('.variant-availability')?.value||'in_stock');if(manual==='hidden')return'hidden';if($('trackInventory')?.checked&&nonNegativeInt(row.querySelector('.variant-quantity')?.value)<=0)return'out_of_stock';return manual==='out_of_stock'?'out_of_stock':'in_stock';}
  function renderVariantGroupControls(){const holder=$('variantGroupControls');if(!holder)return;const rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]),groups=new Map();rows.forEach(row=>{const color=clean(row.querySelector('.variant-color')?.value);if(!color)return;const k=key(color);if(!groups.has(k))groups.set(k,{color,rows:[]});groups.get(k).rows.push(row);});holder.innerHTML=groups.size?`<div class="variant-group-title"><b>Colour availability</b><small>Turn a complete colour on or off without editing every option.</small></div>${Array.from(groups.values()).map(group=>{const available=group.rows.some(row=>effectiveVariantStatus(row)==='in_stock'),total=group.rows.reduce((sum,row)=>sum+nonNegativeInt(row.querySelector('.variant-quantity')?.value),0);return `<label class="variant-group-control"><span><b>${esc(group.color)}</b><small>${group.rows.length} option${group.rows.length===1?'':'s'} · ${total} unit${total===1?'':'s'}</small></span><select data-variant-group-status="${esc(group.color)}"><option value="in_stock" ${available?'selected':''}>Colour available</option><option value="out_of_stock" ${available?'':'selected'}>Colour unavailable</option></select></label>`;}).join('')}`:'';}
  function setVariantGroupStatus(color,state){const target=key(color);$('variantList')?.querySelectorAll('.variant-row').forEach(row=>{if(key(row.querySelector('.variant-color')?.value)!==target)return;const select=row.querySelector('.variant-availability');if(select&&select.value!=='hidden')select.value=state==='out_of_stock'?'out_of_stock':'in_stock';});updateInventoryControls();}
  function renumberVariantRows(){$('variantList')?.querySelectorAll('.variant-row').forEach((row,index)=>{row.dataset.variantIndex=String(index);updateVariantRowTitle(row);});}
  function updateInventoryControls(){const barcodeOn=Boolean($('barcodeEnabled')?.checked),track=Boolean($('trackInventory')?.checked);if($('barcodeValue'))$('barcodeValue').disabled=!barcodeOn;$('barcodeFieldWrap')?.classList.toggle('is-disabled',!barcodeOn);const rows=Array.from($('variantList')?.querySelectorAll('.variant-row')||[]);rows.forEach(row=>{row.querySelector('.variant-quantity-wrap')?.classList.toggle('hide',!track);const qty=row.querySelector('.variant-quantity');if(qty)qty.disabled=!track;if(track&&nonNegativeInt(qty?.value)<=0){const a=row.querySelector('.variant-availability');if(a&&a.value!=='hidden')a.value='out_of_stock';}});const productQty=$('productStockQuantity'),hasVariants=rows.length>0;if(productQty){productQty.disabled=!track||hasVariants;if(track&&hasVariants)productQty.value=String(rows.reduce((s,r)=>s+nonNegativeInt(r.querySelector('.variant-quantity')?.value),0));}$('productStockWrap')?.classList.toggle('is-disabled',!track);if($('stockQuantityHint'))$('stockQuantityHint').textContent=hasVariants?'Calculated automatically from all exact option quantities.':'Enter the available quantity for this product.';if($('inventorySummary')){if(!track)$('inventorySummary').textContent='Stock tracking is off. Availability is controlled manually.';else if(hasVariants){const total=rows.reduce((s,r)=>s+nonNegativeInt(r.querySelector('.variant-quantity')?.value),0),available=rows.filter(r=>effectiveVariantStatus(r)==='in_stock').length;$('inventorySummary').textContent=`${total} total unit${total===1?'':'s'} across ${rows.length} exact variant${rows.length===1?'':'s'} · ${available} currently available.`;}else $('inventorySummary').textContent=`${nonNegativeInt(productQty?.value)} unit${nonNegativeInt(productQty?.value)===1?'':'s'} currently available.`;}renderVariantGroupControls();}
  function renderVariantImages(row){const holder=row?.querySelector('.variant-images');if(!holder)return;const existing=JSON.parse(row.dataset.existingImages||'[]'),files=Array.isArray(row.__variantFiles)?row.__variantFiles:[];holder.innerHTML=existing.map((url,i)=>`<div class="variant-img-chip"><img src="${esc(url)}"><button type="button" data-remove-variant-existing="${i}">×</button></div>`).join('')+files.map((file,i)=>`<div class="variant-img-chip variant-new-image"><img src="${esc(URL.createObjectURL(file))}"><button type="button" data-remove-variant-new="${i}">×</button></div>`).join('')+'<label class="mini-upload">+ Image<input class="variant-files" type="file" accept="image/*" hidden></label>';}
  function quickAddOptions(){
    const mode=clean($('variantSetupMode')?.value||'color_option'),color=clean($('variantBulkColor')?.value),sizes=String($('variantBulkSizes')?.value||'').split(/[,\n|]+/).map(clean).filter(Boolean),qty=nonNegativeInt($('variantBulkQty')?.value),separateQty=Boolean($('variantBulkSeparateQty')?.checked);if(mode==='simple'){status('Choose One option or Colour + option first.','error');return;}if(mode==='color_option'&&!color){status('Enter a colour first.','error');return;}if(!sizes.length){status(`Enter one or more ${variantOptionLabel().toLowerCase()} values.`,'error');return;}if($('variantBulkSeparatePrice')?.checked){const missing=sizes.filter(size=>!bulkRateFor(size));if(missing.length){status(`Enter the final price for ${missing.join(', ')}.`,'error');return;}}
    const existing=new Set(Array.from($('variantList').querySelectorAll('.variant-row')).map(row=>`${key(row.querySelector('.variant-color')?.value||'default')}::${key(row.querySelector('.variant-size')?.value||'standard')}`)),existingLead=mode==='color_option'?Array.from($('variantList').querySelectorAll('.variant-row')).find(row=>key(row.querySelector('.variant-color')?.value)===key(color)):null,addedRows=[];let added=0,skipped=0,first=null;
    sizes.forEach(size=>{const combo=`${key(color||'default')}::${key(size)}`;if(existing.has(combo)){skipped++;return;}existing.add(combo);appendVariantRow({color,size,stockQuantity:separateQty?bulkQtyFor(size):qty,stockStatus:'in_stock',mrp:$('variantBulkSeparatePrice')?.checked?bulkMrpFor(size):'',price:$('variantBulkSeparatePrice')?.checked?bulkRateFor(size):'',images:[],storagePaths:[]});const row=$('variantList').lastElementChild;if(row){const separate=row.querySelector('.variant-separate-price');if(separate)separate.checked=Boolean($('variantBulkSeparatePrice')?.checked);row.querySelector('.variant-price-fields')?.classList.toggle('hide',!separate?.checked);if(!first)first=row;addedRows.push(row);}added++;});
    const file=$('variantBulkSharedImage')?.files?.[0];if(file&&mode==='color_option'){const owner=existingLead||first;if(owner){owner.__variantFiles=[file];const toggle=owner.querySelector('.variant-separate-image');if(toggle)toggle.checked=true;renderVariantImages(owner);}}else if(file&&mode==='option'){addedRows.forEach(row=>{row.__variantFiles=[file];const toggle=row.querySelector('.variant-separate-image');if(toggle)toggle.checked=true;renderVariantImages(row);});}
    updateVariantInheritanceUI();updateInventoryControls();if(added){$('variantBulkSizes').value='';if($('variantBulkSharedImage'))$('variantBulkSharedImage').value='';if($('variantBulkSharedImageName'))$('variantBulkSharedImageName').textContent='No image selected';if($('variantBulkSeparatePrice'))$('variantBulkSeparatePrice').checked=false;if($('variantBulkSeparateQty'))$('variantBulkSeparateQty').checked=false;buildVariantBulkRateTable();updateVariantModeUI();status(`${color?color+': ':''}added ${added} option${added===1?'':'s'}${skipped?` · ${skipped} duplicate skipped`:''}.`,'ok');}else status('Those exact options already exist.','error');
  }
  function collectVariantRows(){return Array.from($('variantList')?.querySelectorAll('.variant-row')||[]).map(row=>({row,id:clean(row.dataset.variantId),color:clean(row.querySelector('.variant-color')?.value),size:clean(row.querySelector('.variant-size')?.value),mrp:row.querySelector('.variant-separate-price')?.checked?price(row.querySelector('.variant-mrp')?.value):'',price:row.querySelector('.variant-separate-price')?.checked?price(row.querySelector('.variant-price')?.value):'',stockQuantity:nonNegativeInt(row.querySelector('.variant-quantity')?.value),stockStatus:effectiveVariantStatus(row),terms:[],existingImages:row.querySelector('.variant-separate-image')?.checked?JSON.parse(row.dataset.existingImages||'[]'):[],existingPaths:row.querySelector('.variant-separate-image')?.checked?JSON.parse(row.dataset.existingPaths||'[]'):[],files:row.querySelector('.variant-separate-image')?.checked&&Array.isArray(row.__variantFiles)?row.__variantFiles:[]})).filter(v=>v.color||v.size||v.mrp||v.price||v.existingImages.length||v.files.length);}
  function exactOptionValues(value){return[...new Map(String(value??'').split(/[,|\n]+/).map(clean).filter(Boolean).map(v=>[key(v),v])).values()];}
  function expandExactVariantDrafts(rows){const out=[];(rows||[]).forEach(item=>{const values=exactOptionValues(item.size);if(values.length<=1){out.push({...item,size:values[0]||item.size});return;}values.forEach((size,index)=>out.push({...item,id:index===0?item.id:'',size,stockQuantity:item.stockQuantity,existingImages:index===0?item.existingImages:[],existingPaths:index===0?item.existingPaths:[],files:index===0?item.files:[]}));});return out;}
  function validateVariantRows(rows){const mode=clean($('variantSetupMode')?.value||inferredVariantMode()),used=new Set();if(mode==='simple'&&rows.length)throw new Error('Simple products cannot contain separate option rows.');for(const item of rows){if(!item.color&&!item.size)throw new Error('Enter an option value for every row.');if(mode==='color_option'&&!item.color)throw new Error('Enter a colour for every colour + option row.');if(mode==='option'&&item.color)throw new Error('Option-only products cannot contain colour values.');const k=`${key(item.color||'default')}::${key(item.size||'standard')}`;if(used.has(k))throw new Error(`Duplicate variant: ${item.color||'Default'} ${item.size||'Standard'}`);used.add(k);}}

  async function ensureUploadGrant(){
    const now=Date.now();if(uploadGrant?.token&&uploadGrant.expiresAt-now>60000)return uploadGrant;
    const {data,error}=await db().rpc('employee_issue_upload_token',{p_token:token()});if(error)throw error;uploadGrant={token:clean(data?.token),expiresAt:Date.parse(data?.expires_at||'')||now+8*60000};if(!uploadGrant.token)throw new Error('Could not prepare image upload.');return uploadGrant;
  }
  async function uploadFile(file,folder='products'){
    if(!file)return null;const grant=await ensureUploadGrant();const ext=(clean(file.name).split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';const random=(crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`);const path=`employee-uploads/${grant.token}/${folder}/${random}.${ext}`;const {error}=await db().storage.from(ADMIN_CONFIG.storageBucket||'product-images').upload(path,file,{cacheControl:'31536000',upsert:false,contentType:file.type||undefined});if(error)throw error;const {data}=db().storage.from(ADMIN_CONFIG.storageBucket||'product-images').getPublicUrl(path);return{url:data?.publicUrl||'',path};
  }
  async function uploadFiles(files,folder){const out=[];for(const file of(files||[])){const item=await uploadFile(file,folder);if(item)out.push(item);}return out;}
  async function collectVariantsPayload(rows){
    const mode=clean($('variantSetupMode')?.value||inferredVariantMode()),variants=[],colourAssets=new Map(),fileAssets=new Map();
    if(mode==='color_option'){
      const groups=new Map();rows.forEach(item=>{const k=key(item.color);if(!k)return;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(item);});
      for(const [k,group] of groups){const newSource=group.find(x=>x.files?.length),existingSource=group.find(x=>x.existingImages?.length),source=newSource||existingSource;if(!source){colourAssets.set(k,{imageUrls:[],storagePaths:[]});continue;}if(newSource){const up=await uploadFiles(newSource.files.slice(0,1),'variants');colourAssets.set(k,{imageUrls:up.map(x=>x.url),storagePaths:up.map(x=>x.path)});}else colourAssets.set(k,{imageUrls:(source.existingImages||[]).slice(0,1),storagePaths:(source.existingPaths||[]).slice(0,1)});}
    }
    for(const item of rows){let imageUrls=[],storagePaths=[];if(mode==='color_option'){const shared=colourAssets.get(key(item.color))||{imageUrls:[],storagePaths:[]};imageUrls=[...shared.imageUrls];storagePaths=[...shared.storagePaths];}else{const assets=[];for(const file of(item.files||[])){if(fileAssets.has(file)){assets.push(fileAssets.get(file));continue;}const up=await uploadFiles([file],'variants');if(up[0]){fileAssets.set(file,up[0]);assets.push(up[0]);}}imageUrls=(item.existingImages||[]).concat(assets.map(x=>x.url));storagePaths=(item.existingPaths||[]).concat(assets.map(x=>x.path));}variants.push({id:item.id||'',color:item.color,size:item.size||'Standard',mrp:item.mrp||'',price:item.price||'',stock:item.stockQuantity||0,stock_status:item.stockStatus||'in_stock',terms:item.terms||[],image_urls:imageUrls,storage_paths:storagePaths});}
    return variants;
  }

  async function openProduct(id){
    busy('Opening product...');try{const {data,error}=await db().rpc('employee_manage_get_product',{p_token:token(),p_product_id:id});if(error)throw error;if(!data)throw new Error('Product not found.');editingProductId=clean(data.id);$('editId').value=editingProductId;$('category').value=clean(data.category_id);$('subcategory').value=clean(data.subcategory_name);renderProductSubcategoryOptions(false);$('productName').value=clean(data.name);$('searchKeywords').value=clean(data.search_keywords);$('mrp').value=price(data.mrp)||'';$('price').value=price(data.price)||'';$('optionTitle').value=clean(data.option_title);$('description').value=clean(data.description);$('availability').value=clean(data.status)!=='active'?'hidden':clean(data.stock_status||'in_stock');$('barcodeEnabled').checked=data.barcode_enabled===true;$('barcodeValue').value=clean(data.barcode);$('trackInventory').checked=data.track_inventory===true;$('productStockQuantity').value=String(Math.max(0,Number(data.stock_quantity||0)));currentImages=(data.images||[]).map(i=>({url:clean(i.image_url),path:clean(i.storage_path)})).filter(i=>i.url);newImageFiles=[];renderImagePreviews();renderTermChecks(splitList(data.terms||[]));const variants=(data.variants||[]).map(v=>({id:v.id,color:clean(v.color||v.unit),size:clean(v.size||v.label),mrp:price(v.mrp)||'',price:price(v.price)||'',images:splitList(v.image_urls||v.image_url||[]),storagePaths:splitList(v.storage_paths||[]),stockQuantity:Math.max(0,Number(v.stock||0)),stockStatus:clean(v.stock_status||'in_stock')}));renderVariantRows(variants);$('formTitle').textContent='Edit product';$('saveBtn').textContent='Update Product';$('deleteBtn').style.display='inline-flex';$('cancelEditBtn').classList.remove('hide');switchManagerView('editor');status(`${clean(data.name)} ready to edit.`,'ok');}finally{idle();}
  }
  async function saveProduct(event){
    event.preventDefault();if(saveInProgress)return;saveInProgress=true;$('saveBtn').disabled=true;busy(editingProductId?'Updating product...':'Saving product...');
    try{
      requireSession();const categoryId=clean($('category').value),category=categories.find(c=>c.id===categoryId),name=clean($('productName').value);if(!category||!name)throw new Error('Select category and enter the product name.');const mode=clean($('variantSetupMode').value||'simple'),drafts=expandExactVariantDrafts(collectVariantRows());validateVariantRows(drafts);let mainPrice=price($('price').value);const firstRate=drafts.map(v=>price(v.price)).find(Boolean)||'';if(mode==='simple'&&!mainPrice)throw new Error('Enter the final price for this product.');if(mode!=='simple'&&!mainPrice)mainPrice=firstRate;if(!mainPrice)throw new Error('Enter a main final price, or enter a separate final price for every option.');if(mode==='color_option'){const groups=new Map();drafts.forEach(v=>{const k=key(v.color);if(k&&!groups.has(k))groups.set(k,v);});for(const lead of groups.values())if(!lead.existingImages.length&&!lead.files.length)throw new Error(`Add one image for ${lead.color}. It will be reused for every option in that colour.`);}const barcodeEnabled=Boolean($('barcodeEnabled').checked),barcode=clean($('barcodeValue').value);if(barcodeEnabled&&!barcode)throw new Error('Enter a barcode, or turn Barcode identification off.');const track=Boolean($('trackInventory').checked);if(!editingProductId&&!currentImages.length&&!newImageFiles.length&&!drafts.some(v=>v.files.length||v.existingImages.length))throw new Error('Choose at least one product image or option image.');
      const newMain=await uploadFiles(newImageFiles,'products'),allImages=currentImages.concat(newMain),variants=await collectVariantsPayload(drafts),availability=clean($('availability').value||'in_stock'),visible=variants.filter(v=>v.stock_status!=='hidden'),calculated=variants.length?visible.reduce((s,v)=>s+nonNegativeInt(v.stock),0):nonNegativeInt($('productStockQuantity').value),anyAvailable=visible.some(v=>v.stock_status==='in_stock'&&(!track||nonNegativeInt(v.stock)>0)),trackedStatus=variants.length?(anyAvailable?'in_stock':'out_of_stock'):(calculated>0?'in_stock':'out_of_stock'),visibleSizes=[...new Set(visible.map(v=>clean(v.size)).filter(Boolean))].join(', '),visibleColors=[...new Set(visible.map(v=>clean(v.color)).filter(Boolean))].join(', '),productSizes=mode==='simple'?'Standard':(visibleSizes||'Standard'),productColors=mode==='color_option'?(visibleColors||'Default'):'Default',allHidden=variants.length>0&&visible.length===0,mainMrp=price($('mrp').value)||drafts.map(v=>price(v.mrp)).find(Boolean)||'';
      const firstVariantImage=variants.flatMap(v=>v.image_urls||[]).find(Boolean)||'';
      const payload={id:editingProductId||'',category_id:category.id,subcategory_id:'',subcategory_name:clean($('subcategory').value),name,slug:slugify(name)+'-'+Date.now(),description:clean($('description').value),search_keywords:clean($('searchKeywords').value),mrp:mainMrp||'',price:mainPrice||'',main_image_url:allImages[0]?.url||firstVariantImage,option_title:mode==='simple'?'':clean($('optionTitle').value),sizes:productSizes,colors:productColors,terms:selectedProductTerms(),status:availability==='hidden'?'hidden':'active',stock_status:allHidden?'out_of_stock':(track?trackedStatus:(availability==='out_of_stock'?'out_of_stock':'in_stock')),stock_quantity:track?calculated:0,track_inventory:track,barcode:barcode||'',barcode_enabled:barcodeEnabled,images:allImages.map((img,i)=>({url:img.url,path:img.path||'',sort_order:i})),variants:variants.map((v,i)=>({...v,sort_order:i}))};
      const wasEditing=Boolean(editingProductId);const {data,error}=await db().rpc('employee_manage_save_product',{p_token:token(),p_payload:payload});if(error)throw error;await broadcastStoreChange(editingProductId?'employee-product-update':'employee-product-insert',clean(data));await loadMeta();await loadProducts(true);resetProduct(false);switchManagerView('products');status(wasEditing?'Product updated ✅':'Product saved ✅','ok');
    }catch(error){if(!sessionError(error))status(error.message||'Could not save product.','error');}
    finally{idle();saveInProgress=false;if($('saveBtn'))$('saveBtn').disabled=false;}
  }
  async function deleteProduct(){const id=clean(editingProductId||$('editId')?.value);if(!id)return;if(!confirm('Delete this product?'))return;busy('Deleting product...');try{const {error}=await db().rpc('employee_manage_delete_product',{p_token:token(),p_product_id:id});if(error)throw error;await broadcastStoreChange('employee-product-delete',id);await loadProducts(true);resetProduct(false);switchManagerView('products');status('Product deleted.','ok');}catch(error){if(!sessionError(error))status(error.message||'Could not delete product.','error');}finally{idle();}}
  async function broadcastStoreChange(action,productId){try{const ch=db().channel(`employee-manage-${Date.now()}`,{config:{broadcast:{ack:false}}});await new Promise(resolve=>{const timer=setTimeout(resolve,700);ch.subscribe(state=>{if(state==='SUBSCRIBED'){clearTimeout(timer);resolve();}});});await ch.send({type:'broadcast',event:'store-change',payload:{tables:['products','product_images','product_variants'],action,details:{productId},eventId:`employee-manage-${Date.now()}`,at:Date.now()}});db().removeChannel(ch);}catch(_e){}}

  function bind(){
    $('employeeSaleTab')?.addEventListener('click',()=>openMode('sale'));
    $('employeeManageTab')?.addEventListener('click',()=>openMode('manage'));
    $('newProductBtn')?.addEventListener('click',()=>resetProduct(true));
    $('reloadProductsBtn')?.addEventListener('click',()=>loadProducts(true).catch(e=>status(e.message,'error')));
    $('productCategoryFilter')?.addEventListener('change',()=>loadProducts(true).catch(e=>status(e.message,'error')));
    $('searchProducts')?.addEventListener('input',()=>{clearTimeout(window.__employeeManageSearch);window.__employeeManageSearch=setTimeout(()=>loadProducts(true).catch(e=>status(e.message,'error')),300);});
    $('loadMoreProductsBtn')?.addEventListener('click',()=>loadProducts(false).catch(e=>status(e.message,'error')));
    $('category')?.addEventListener('change',()=>{$('subcategory').value='';renderProductSubcategoryOptions(false);});
    $('subcategory')?.addEventListener('focus',()=>renderProductSubcategoryOptions(true));$('subcategory')?.addEventListener('input',()=>renderProductSubcategoryOptions(true));
    $('subcategoryToggle')?.addEventListener('click',()=>{const open=$('subcategoryCombobox').classList.contains('open');renderProductSubcategoryOptions(!open);if(!open)$('subcategory').focus();});
    $('photoPicker')?.addEventListener('click',()=>$('photoInput')?.click());$('photoInput')?.addEventListener('change',()=>{newImageFiles.push(...Array.from($('photoInput').files||[]));$('photoInput').value='';renderImagePreviews();});$('clearAllImagesBtn')?.addEventListener('click',clearProductImages);
    $('addVariantBtn')?.addEventListener('click',e=>{e.preventDefault();appendVariantRow({color:'',size:'',images:[],storagePaths:[]});});$('addColourSizesBtn')?.addEventListener('click',quickAddOptions);$('variantBulkSizes')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();quickAddOptions();}});$('variantBulkSizes')?.addEventListener('input',buildVariantBulkRateTable);$('variantBulkSeparatePrice')?.addEventListener('change',buildVariantBulkRateTable);$('variantBulkSeparateQty')?.addEventListener('change',()=>{if($('variantBulkSeparateQty').checked)$('trackInventory').checked=true;buildVariantBulkRateTable();updateInventoryControls();});$('variantBulkSharedImageBtn')?.addEventListener('click',()=>$('variantBulkSharedImage')?.click());$('variantBulkSharedImage')?.addEventListener('change',()=>{const file=$('variantBulkSharedImage')?.files?.[0];$('variantBulkSharedImageName').textContent=file?file.name:'No image selected';});$('variantSetupMode')?.addEventListener('change',handleVariantModeChange);$('optionTitle')?.addEventListener('input',updateVariantModeUI);$('barcodeEnabled')?.addEventListener('change',updateInventoryControls);$('trackInventory')?.addEventListener('change',updateInventoryControls);$('productStockQuantity')?.addEventListener('input',updateInventoryControls);
    $('productForm')?.addEventListener('submit',saveProduct);$('deleteBtn')?.addEventListener('click',deleteProduct);$('cancelEditBtn')?.addEventListener('click',()=>{resetProduct(false);switchManagerView('products');status('Manage products','');});
    document.addEventListener('click',event=>{if(!$('employeeManageView')?.contains(event.target))return;const sub=event.target.closest('[data-subcategory-option]');if(sub){$('subcategory').value=clean(sub.dataset.subcategoryOption);renderProductSubcategoryOptions(false);return;}if(!event.target.closest('#subcategoryCombobox'))setSubcategoryDropdown(false);const edit=event.target.closest('[data-edit]');if(edit){openProduct(edit.dataset.edit).catch(error=>{idle();if(!sessionError(error))status(error.message,'error');});return;}const re=event.target.closest('[data-remove-existing-image]');if(re){currentImages.splice(Number(re.dataset.removeExistingImage),1);renderImagePreviews();return;}const rn=event.target.closest('[data-remove-new-image]');if(rn){newImageFiles.splice(Number(rn.dataset.removeNewImage),1);renderImagePreviews();return;}const rv=event.target.closest('[data-remove-variant]');if(rv){rv.closest('.variant-row')?.remove();if(!$('variantList').querySelector('.variant-row'))renderVariantRows([]);else renumberVariantRows();updateInventoryControls();return;}const old=event.target.closest('[data-remove-variant-existing]');if(old){const row=old.closest('.variant-row'),idx=Number(old.dataset.removeVariantExisting||0),imgs=JSON.parse(row.dataset.existingImages||'[]'),paths=JSON.parse(row.dataset.existingPaths||'[]');imgs.splice(idx,1);paths.splice(idx,1);row.dataset.existingImages=JSON.stringify(imgs);row.dataset.existingPaths=JSON.stringify(paths);renderVariantImages(row);return;}const fresh=event.target.closest('[data-remove-variant-new]');if(fresh){const row=fresh.closest('.variant-row');row.__variantFiles=Array.isArray(row.__variantFiles)?row.__variantFiles:[];row.__variantFiles.splice(Number(fresh.dataset.removeVariantNew||0),1);renderVariantImages(row);}});
    document.addEventListener('change',event=>{if(!$('employeeManageView')?.contains(event.target))return;if(event.target.matches('[data-variant-group-status]')){setVariantGroupStatus(event.target.dataset.variantGroupStatus,event.target.value);return;}if(event.target.classList.contains('variant-availability'))updateInventoryControls();if(event.target.classList.contains('variant-separate-price')){const row=event.target.closest('.variant-row');row?.querySelector('.variant-price-fields')?.classList.toggle('hide',!event.target.checked);syncMainPricingVisibility();}if(event.target.classList.contains('variant-separate-image')){event.target.closest('.variant-row')?.querySelector('.variant-image-section')?.classList.toggle('hide',!event.target.checked);}if(event.target.classList.contains('variant-files')){const row=event.target.closest('.variant-row');if(row){row.__variantFiles=Array.from(event.target.files||[]).slice(0,1);event.target.value='';const toggle=row.querySelector('.variant-separate-image');if(toggle)toggle.checked=true;renderVariantImages(row);updateVariantInheritanceUI();}}});
    document.addEventListener('input',event=>{if(!$('employeeManageView')?.contains(event.target))return;if(event.target.classList.contains('variant-color')||event.target.classList.contains('variant-size')){updateVariantRowTitle(event.target.closest('.variant-row'));updateVariantInheritanceUI();renderVariantGroupControls();}if(event.target.classList.contains('variant-quantity'))updateInventoryControls();if(event.target.classList.contains('variant-price'))syncMainPricingVisibility();});
  }
  bind();renderTermChecks();renderVariantRows([]);updateInventoryControls();switchManagerView('products');
})();
