'use strict';
const CACHE_VERSION='wellone-employee-v100-product-manager';
const SHELL_CACHE=`${CACHE_VERSION}-shell`;
const RUNTIME_CACHE=`${CACHE_VERSION}-runtime`;
const SHELL=['./','./index.html','./css/admin.css?v=100','./js/employee.bundle.js?v=100','./js/pwa-install.js?v=100','./manifest.webmanifest','./assets/logo.png?v=100','./assets/favicon/favicon.ico'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(SHELL_CACHE);await Promise.allSettled(SHELL.map(url=>cache.add(url)));await self.skipWaiting();})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(key=>key.startsWith('wellone-employee-')&&!key.startsWith(CACHE_VERSION)).map(key=>caches.delete(key)));await self.clients.claim();})()));
function u(request){try{return new URL(request.url)}catch(_e){return null}}
function storage(url){return !!url&&url.pathname.includes('/storage/v1/object/public/')}
function supabaseApi(url){return !!url&&url.hostname.endsWith('.supabase.co')&&!storage(url)}
async function trim(name,max=120){const cache=await caches.open(name),keys=await cache.keys();if(keys.length>max)await Promise.all(keys.slice(0,keys.length-max).map(k=>cache.delete(k)));}
async function put(request,response){if(response&&(response.ok||response.type==='opaque')){const cache=await caches.open(RUNTIME_CACHE);await cache.put(request,response.clone()).catch(()=>{});trim(RUNTIME_CACHE).catch(()=>{});}}
async function cacheFirst(request){const cached=await caches.match(request);if(cached)return cached;const response=await fetch(request);put(request,response).catch(()=>{});return response;}
async function stale(request){const cached=await caches.match(request);const network=fetch(request).then(r=>{put(request,r).catch(()=>{});return r;}).catch(()=>null);if(cached){network.catch(()=>{});return cached;}const response=await network;if(response)return response;throw new Error('Network unavailable');}
async function navigate(request){const url=u(request);url.search='';url.hash='';const canonical=new Request(url.href,{headers:{Accept:'text/html'}});const cached=(await caches.match(canonical))||(await caches.match('./index.html'));if(cached){fetch(request,{cache:'no-cache'}).then(r=>{if(r&&r.ok)caches.open(SHELL_CACHE).then(c=>c.put(canonical,r.clone())).catch(()=>{});}).catch(()=>{});return cached;}try{const r=await fetch(request,{cache:'no-cache'});if(r&&r.ok)caches.open(SHELL_CACHE).then(c=>c.put(canonical,r.clone())).catch(()=>{});return r;}catch(_e){return new Response('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><p style="font-family:system-ui;padding:24px">Connection unavailable. Please try again.</p>',{status:503,headers:{'Content-Type':'text/html'}});}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=u(request);if(!url)return;if(request.mode==='navigate'){event.respondWith(navigate(request));return;}if(supabaseApi(url)){event.respondWith(fetch(request,{cache:'no-store'}));return;}const same=url.origin===self.location.origin;const versioned=same&&/(?:\?|&)v=100(?:&|$)/.test(url.search);const staticAsset=same&&['script','style','manifest','font'].includes(request.destination);const image=request.destination==='image'||storage(url);if(versioned||staticAsset||url.hostname==='cdn.jsdelivr.net'){event.respondWith(cacheFirst(request));return;}if(image||same)event.respondWith(stale(request));});
